name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '.nvmrc'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Start http-server
        run: |
          npm run start &
          npx wait-on http://localhost:8080

      - name: Run Cypress tests
        run: npx cypress run
